server:
  port: 8081

spring:
  application:
    name: auth-service

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: auth_schema
        format_sql: true
    open-in-view: false
    show-sql: false

  flyway:
    enabled: true
    schemas: auth_schema
    baseline-on-migrate: false
    validate-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    org.hibernate.SQL: INFO
    org.flywaydb: INFO

jwt:
  secret: ${JWT_SECRET:dev-only-secret-not-for-production-CHANGE-ME-please-min-32-chars}
  access-expiration: PT15M
  refresh-expiration: P7D
