services:
  auth-uri: http://localhost:8081
  task-uri: http://localhost:8082

server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service-route
              uri: ${services.auth-uri}
              predicates:
                - Path=/auth/**
            - id: task-service-route
              uri: ${services.task-uri}
              predicates:
                - Path=/tasks/**,/categories/**,/me/activity/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: taskServiceBreaker
                    fallbackUri: forward:/fallback/tasks
            - id: auth-users-route
              uri: ${services.auth-uri}
              predicates:
                - Path=/users/**

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway, circuitbreakers, circuitbreakerevents
  endpoint:
    health:
      show-details: always
    gateway:
      access: read-only
  health:
    circuitbreakers:
      enabled: true

jwt:
  secret: ${JWT_SECRET:ZGV2T25seVNlY3JldE5vdEZvclByb2R1Y3Rpb25DaGFuZ2VNZVBsZWFzZU1pbjMyQ2hhcnM=}

resilience4j:
  circuitbreaker:
    instances:
      taskServiceBreaker:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
