server:
  port: 8082

spring:
  application:
    name: task-service

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: task_schema
        format_sql: true
    open-in-view: false
    show-sql: false

  flyway:
    enabled: true
    schemas: task_schema
    baseline-on-migrate: false
    validate-on-migrate: true

  data:
    mongodb:
      database: taskmanager
      auto-index-creation: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      
management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    org.hibernate.SQL: INFO
    org.flywaydb: INFO
    org.mongodb.driver: WARN
